<?php

return [
  'generation_fieldid' => [
    'name' => 'generation_fieldid',
    'group' => 'mygeneration',
    'group_name' => 'My Generation Settings',
    'type' => 'Integer',
    'html_type' => 'text',
    'title' => ts('Generation Field ID'),
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['mygeneration' => ['weight' => 10]],
  ],
  'generation_builder' => [
    'name' => 'generation_builder',
    'group' => 'mygeneration',
    'group_name' => 'My Generation Settings',
    'type' => 'Integer',
    'html_type' => 'text',
    'title' => ts('Builder Generation, Option Value'),
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['mygeneration' => ['weight' => 10]],
  ],
  'generation_boomer' => [
    'name' => 'generation_boomer',
    'group' => 'mygeneration',
    'group_name' => 'My Generation Settings',
    'type' => 'Integer',
    'html_type' => 'text',
    'title' => ts('Boomer Generation, Option Value'),
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['mygeneration' => ['weight' => 10]],
  ],
  'generation_genx' => [
    'name' => 'generation_genx',
    'group' => 'mygeneration',
    'group_name' => 'My Generation Settings',
    'type' => 'Integer',
    'html_type' => 'text',
    'title' => ts('Gen X Generation, Option Value'),
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['mygeneration' => ['weight' => 10]],
  ],
  'generation_geny' => [
    'name' => 'generation_geny',
    'group' => 'mygeneration',
    'group_name' => 'My Generation Settings',
    'type' => 'Integer',
    'html_type' => 'text',
    'title' => ts('Gen Y Generation, Option Value'),
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['mygeneration' => ['weight' => 10]],
  ],
  'generation_genz' => [
    'name' => 'generation_genz',
    'group' => 'mygeneration',
    'group_name' => 'My Generation Settings',
    'type' => 'Integer',
    'html_type' => 'text',
    'title' => ts('Gen Z Generation, Option Value'),
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['mygeneration' => ['weight' => 10]],
  ],
];